# Recursive Feature Elimination (RFE)

In [36]:
from sklearn.datasets import load_wine
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [37]:
X,y  = load_wine(return_X_y=True,as_frame=True)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((124, 13), (54, 13), (124,), (54,))

In [38]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

In [39]:
from sklearn.linear_model import LogisticRegression
clf =  LogisticRegression()
clf.fit(X_train_std,y_train)
clf.score(X_test_std,y_test)

0.9814814814814815

In [41]:
from sklearn.feature_selection  import RFE
# RFE 使用的評估演算法必須支援 coef_ or feature_importances_ 屬性，KNN 不適用

clf = LogisticRegression()
model = RFE(clf,n_features_to_select=3)
model.fit(X_train_std,y_train)
model.get_support()

array([False, False, False, False, False, False,  True, False, False,
       False,  True, False,  True])

In [9]:
clf = LogisticRegression()
clf.fit(model.transform(X_train_std),y_train)

LogisticRegression()

In [10]:
clf.score(model.transform(X_test_std),y_test)

0.9814814814814815

### 什麼是交叉驗證？

交叉驗證是一種評估機器學習模型性能的技術。其主要目的是確保模型在新數據上的泛化能力。交叉驗證通過將數據集分成多個子集，然後對每個子集進行訓練和測試來實現這一目標。

### 交叉驗證的方法

1. **K折交叉驗證（K-Fold Cross-Validation）**
   - 數據集被分成K個等分的子集。
   - 每次使用K-1個子集進行訓練，剩下一個子集進行測試。
   - 重複K次，每次選擇不同的子集作為測試集，最終取平均值作為模型性能評估。
2. **分層K折交叉驗證（Stratified K-Fold Cross-Validation）**
   - 適用於分類問題，確保每個子集中各類別樣本的比例與原始數據集相同。

3. **隨機劃分交叉驗證（Shuffle-Split Cross-Validation）**
   - 每次隨機打亂數據集並劃分為訓練集和測試集。
   - 重複多次，取平均值作為模型性能評估。

### 交叉驗證的哲學

交叉驗證的核心理念是通過多次訓練和測試來更全面地評估模型的性能。這樣可以減少模型過擬合的風險，並確保模型能夠在不同的數據上保持穩定的表現。

### K折交叉驗證（K-Fold Cross-Validation）實際案例

假設我們有一個包含100個樣本的數據集，並且我們選擇K=5進行K折交叉驗證。這意味著我們將數據集分成5個等大小的子集，每個子集包含20個樣本。以下是K折交叉驗證的過程：

1. **數據集劃分**：
   - Fold 1: 樣本1-20
   - Fold 2: 樣本21-40
   - Fold 3: 樣本41-60
   - Fold 4: 樣本61-80
   - Fold 5: 樣本81-100

2. **迭代過程**：
   - **第一次迭代**：
     - 訓練集：Fold 2, Fold 3, Fold 4, Fold 5
     - 測試集：Fold 1
   - **第二次迭代**：
     - 訓練集：Fold 1, Fold 3, Fold 4, Fold 5
     - 測試集：Fold 2
   - **第三次迭代**：
     - 訓練集：Fold 1, Fold 2, Fold 4, Fold 5
     - 測試集：Fold 3
   - **第四次迭代**：
     - 訓練集：Fold 1, Fold 2, Fold 3, Fold 5
     - 測試集：Fold 4
   - **第五次迭代**：
     - 訓練集：Fold 1, Fold 2, Fold 3, Fold 4
     - 測試集：Fold 5

3. **結果評估**：每次迭代都會得到一個模型性能評估指標（如準確率），最終取這5個指標的平均值作為模型的最終性能評估。

In [11]:
df = pd.read_csv("./Advertising.csv")
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [12]:
from sklearn.linear_model import Ridge
X = df.drop("sales",axis=1)
y = df["sales"]

In [20]:
len(X),len(y),len(X.columns)

(200, 200, 3)

In [16]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((140, 3), (60, 3), (140,), (60,))

In [26]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

In [27]:
model = Ridge(alpha=100)
model.fit(X_train_std,y_train)
model.score(X_test_std,y_test)

0.7111732735477903

In [28]:
model.score(X_train_std,y_train)

0.7628206825029008

In [24]:
model = Ridge(alpha=100)

In [30]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(model,X_train_std,y_train,cv=5)
print(score)
print(score.mean())

[0.66640169 0.7261125  0.69114235 0.74705142 0.61124758]
0.6883911080223275

## RFECV

In [31]:
X,y = load_wine(return_X_y=True,as_frame=True)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

In [ ]:
from sklearn.feature_selection import RFECV
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()
#min_features_to_select 最少選取3個特徵
model = RFECV(clf,min_features_to_select=3,cv=5)
model.fit(X_train_std,y_train)
model.get_support()

array([ True, False,  True,  True, False, False,  True, False, False,
        True,  True,  True,  True])

In [33]:
clf = LogisticRegression()
clf.fit(model.transform(X_train_std),y_train)

LogisticRegression()

In [34]:
clf.score(model.transform(X_test_std),y_test)

1.0

## Permutation Feature Importance（PFI）

In [62]:
X,y = load_wine(return_X_y=True,as_frame=True)
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

In [79]:
from sklearn.inspection import permutation_importance
clf = KNeighborsClassifier(n_neighbors=5)
clf.fit(X_train_std,y_train)
#n_repeats 打亂次數10次
model = permutation_importance(clf,X_test_std,y_test,n_repeats=10)
model.importances_mean,model.importances_std

(array([ 0.04074074,  0.00925926,  0.01481481,  0.00740741,  0.02037037,
        -0.01851852,  0.01111111,  0.01666667,  0.01111111,  0.07592593,
         0.00185185, -0.00555556,  0.06666667]),
 array([0.01814437, 0.01493011, 0.01385799, 0.0169725 , 0.01296296,
        0.01434438, 0.02371527, 0.01296296, 0.01481481, 0.02260473,
        0.01538264, 0.00848625, 0.0169725 ]))

In [80]:
#2倍標準差作為平均值是否穩定的標準
# 根據importances_mean 高到低排序
# 找到符合2倍標準差標準的欄位
column_selected = []
meanArgSort = model.importances_mean.argsort()
for i in meanArgSort[::-1]:
    if model.importances_mean[i] - 2 * model.importances_std[i] > 0:
        column_selected.append(X.columns[i])
print(column_selected)

['color_intensity', 'proline', 'alcohol']

In [81]:
X,y = load_wine(return_X_y=True,as_frame=True)
X = X[column_selected]
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((124, 3), (54, 3), (124,), (54,))

In [82]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

In [83]:
clf = LogisticRegression()
clf.fit(X_train_std,y_train)
clf.score(X_test_std,y_test)

0.8888888888888888

# Scikit-learn PCA 實作

PCA 做的事像這樣：

先找一條「最重要的線」
這條線的方向是：
資料沿著它分散得最開（變異最大）
也就是「最能看出差異」的方向。
這條線叫 第一主成分（PC1）。

把每個點「打到這條線上」（投影）
你原本每個點有很多特徵（很多維），
投影後，你只要記得它在線上的位置（1 個數字）就好。
→ 多維變 1 維

如果你要保留更多資訊
再找第二條方向（PC2）：

它也要讓變異大

但不能跟第一條重複（要垂直/獨立）
然後投影到 PC1 + PC2 平面上
→ 多維變 2 維

In [84]:
from sklearn import datasets
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [86]:
ds = datasets.load_wine()
df = pd.DataFrame(ds.data,columns=ds.feature_names)
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0

In [87]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
X = df.values
y = ds.target
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((124, 13), (54, 13), (124,), (54,))

In [88]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_std = scaler.fit_transform(X_train)
X_test_std = scaler.transform(X_test)

In [89]:
from sklearn.decomposition import PCA
pca1 = PCA(n_components=2)
X_train_pca = pca1.fit_transform(X_train_std)
X_test_pca = pca1.transform(X_test_std)
X_train_pca.shape,X_test_pca.shape

((124, 2), (54, 2))

In [91]:
X_train_std[:10],X_train_pca[:10]

(array([[ 2.28652946e-01,  1.49923925e+00, -3.05766905e-01,
         -5.78113418e-01,  2.55906803e-01,  4.98559100e-01,
          5.09439749e-01, -2.95895984e-01,  4.90125741e-02,
         -3.86984343e-01, -5.76086701e-01,  5.02963693e-01,
         -2.43507231e-01],
        [ 5.55942413e-01, -4.69832531e-01,  1.03900498e+00,
         -9.63522363e-02,  7.56193077e-01,  5.24733762e-02,
          4.12715620e-01, -5.41048114e-01, -1.57006382e-01,
         -4.57024203e-01,  6.58892940e-01,  3.19113926e-01,
          1.02249419e+00],
        [ 4.10480428e-01, -4.96929849e-01,  9.26940657e-01,
         -1.02775719e+00, -4.58787873e-01,  8.21586692e-01,
          8.09284550e-01, -1.32461231e-01, -3.11520598e-01,
         -1.94374728e-01, -1.35022544e-01,  8.14094068e-01,
          1.32755478e+00],
        [-1.56537821e+00,  3.25022132e-01,  2.04758390e+00,
          2.24821885e-01,  2.55906803e-01, -8.70462603e-01,
         -7.09050271e-02,  1.99219056e+00, -9.98250450e-01,
         -6.32123852e-01,  1.23227634e+00, -2.04150796e-01,
         -4.66201457e-01],
        [-1.66186408e-03,  1.39084998e+00, -1.93702581e-01,
          1.02775719e+00, -1.03054361e+00, -1.02428527e+00,
         -4.96491196e-01,  2.07390793e+00, -1.96604111e-02,
         -1.94374728e-01, -4.87873870e-01, -8.97122995e-01,
         -7.46857195e-01],
        [ 1.56205448e+00, -5.78221803e-01,  1.22577885e+00,
          1.83069249e+00, -1.01440535e-01,  7.44675361e-01,
         -7.67318759e-01,  1.42016892e+00,  1.83451019e+00,
          3.39516809e+00, -1.67874709e+00, -9.67834444e-01,
         -3.04519348e-01],
        [-9.71408433e-01,  1.40891485e+00, -6.41959876e-01,
         -2.56939297e-01,  8.99132012e-01, -1.43960646e+00,
         -1.27995664e+00, -5.41048114e-01, -8.43736234e-01,
          1.29834978e+00, -1.32589577e+00, -9.11265285e-01,
          2.90348791e-01],
        [ 1.00445020e+00, -3.88540577e-01,  8.14876333e-01,
         -1.38104872e+00,  1.12967868e-01,  1.43687735e+00,
          1.40897415e+00, -1.52165663e+00,  1.17685559e-01,
          8.14072196e-02, -3.11448207e-01,  1.29493192e+00,
          1.02249419e+00],
        [ 1.38022700e+00, -6.59513757e-01,  4.03973812e-01,
         -8.99287538e-01,  6.13254141e-01,  1.51378868e+00,
          1.76685343e+00, -2.95895984e-01,  3.92377500e-01,
          1.51284685e+00,  1.23227634e+00,  2.48402477e-01,
          2.80709861e+00],
        [-3.41073163e-01,  6.30813909e-02, -3.43121680e-01,
          6.42348242e-02, -9.59074146e-01, -1.42422419e+00,
         -1.54111179e+00,  1.01158204e+00, -1.70214855e+00,
          2.03814537e+00, -1.67874709e+00, -1.43453001e+00,
         -8.84134457e-01]]),
 array([[-0.32079554, -0.17194403],
        [-1.28036511, -0.59306597],
        [-1.67174774, -0.56296103],
        [ 1.38484714,  0.66525522],
        [ 2.67134154,  0.15436247],
        [ 1.20567835, -3.36678895],
        [ 2.26651711, -1.13127674],
        [-2.9454904 , -0.94324427],
        [-3.38525538, -2.42402508],
        [ 3.67414636, -0.88419983]]))